// Mocks generated by Mockito 5.4.6 from annotations
// in dance_analysis_client/test/state/upload_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dance_analysis_client/features/history/data/history_repository.dart'
    as _i9;
import 'package:dance_analysis_client/features/upload/domain/repositories/video_repository.dart'
    as _i3;
import 'package:dance_analysis_client/features/upload/presentation/controllers/upload_state.dart'
    as _i5;
import 'package:dance_analysis_client/generated/api/export.dart' as _i2;
import 'package:dance_analysis_client/models/feedback_item.dart' as _i12;
import 'package:dance_analysis_client/models/history_item.dart' as _i11;
import 'package:dance_analysis_client/models/submission.dart' as _i10;
import 'package:dance_analysis_client/shared/services/api_service.dart' as _i7;
import 'package:image_picker/image_picker.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeRestClient_0 extends _i1.SmartFake implements _i2.RestClient {
  _FakeRestClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [VideoRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockVideoRepository extends _i1.Mock implements _i3.VideoRepository {
  MockVideoRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.SelectedVideo?> pickVideo(_i6.ImageSource? source) =>
      (super.noSuchMethod(
            Invocation.method(#pickVideo, [source]),
            returnValue: _i4.Future<_i5.SelectedVideo?>.value(),
          )
          as _i4.Future<_i5.SelectedVideo?>);
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i7.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.RestClient get client =>
      (super.noSuchMethod(
            Invocation.getter(#client),
            returnValue: _FakeRestClient_0(this, Invocation.getter(#client)),
          )
          as _i2.RestClient);

  @override
  void setAuthToken(String? token) => super.noSuchMethod(
    Invocation.method(#setAuthToken, [token]),
    returnValueForMissingStub: null,
  );

  @override
  void clearAuthToken() => super.noSuchMethod(
    Invocation.method(#clearAuthToken, []),
    returnValueForMissingStub: null,
  );

  @override
  void attachTokenRefreshInterceptor({
    required _i4.Future<String?> Function()? refreshAccessToken,
    required _i4.Future<void> Function()? onSessionExpired,
  }) => super.noSuchMethod(
    Invocation.method(#attachTokenRefreshInterceptor, [], {
      #refreshAccessToken: refreshAccessToken,
      #onSessionExpired: onSessionExpired,
    }),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<String> uploadAndSubmitVideo(
    _i5.SelectedVideo? video, {
    void Function(int, int)? onSendProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #uploadAndSubmitVideo,
              [video],
              {#onSendProgress: onSendProgress},
            ),
            returnValue: _i4.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(
                  #uploadAndSubmitVideo,
                  [video],
                  {#onSendProgress: onSendProgress},
                ),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<Map<String, dynamic>> getJobStatus(String? jobId) =>
      (super.noSuchMethod(
            Invocation.method(#getJobStatus, [jobId]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> getJobResult(String? jobId) =>
      (super.noSuchMethod(
            Invocation.method(#getJobResult, [jobId]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [HistoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHistoryRepository extends _i1.Mock implements _i9.HistoryRepository {
  MockHistoryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> recordSubmission(_i10.Submission? submission) =>
      (super.noSuchMethod(
            Invocation.method(#recordSubmission, [submission]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  List<_i10.Submission> getLocalSubmissions() =>
      (super.noSuchMethod(
            Invocation.method(#getLocalSubmissions, []),
            returnValue: <_i10.Submission>[],
          )
          as List<_i10.Submission>);

  @override
  _i4.Future<({List<_i11.HistoryItem> items, String? warning})> loadHistory() =>
      (super.noSuchMethod(
            Invocation.method(#loadHistory, []),
            returnValue:
                _i4.Future<
                  ({List<_i11.HistoryItem> items, String? warning})
                >.value((items: <_i11.HistoryItem>[], warning: null)),
          )
          as _i4.Future<({List<_i11.HistoryItem> items, String? warning})>);

  @override
  _i4.Future<void> hideJob(String? jobId) =>
      (super.noSuchMethod(
            Invocation.method(#hideJob, [jobId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i12.FeedbackItem>> getJobFeedback(String? jobId) =>
      (super.noSuchMethod(
            Invocation.method(#getJobFeedback, [jobId]),
            returnValue: _i4.Future<List<_i12.FeedbackItem>>.value(
              <_i12.FeedbackItem>[],
            ),
          )
          as _i4.Future<List<_i12.FeedbackItem>>);
}
