// Mocks generated by Mockito 5.4.6 from annotations
// in dance_analysis_client/test/state/upload_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:dance_analysis_client/features/upload/domain/repositories/storage_repository.dart'
    as _i6;
import 'package:dance_analysis_client/features/upload/domain/repositories/video_repository.dart'
    as _i2;
import 'package:dance_analysis_client/features/upload/presentation/controllers/upload_state.dart'
    as _i4;
import 'package:dance_analysis_client/models/dance_style.dart' as _i9;
import 'package:dance_analysis_client/models/video_timestamp.dart' as _i10;
import 'package:dance_analysis_client/shared/services/api_client.dart' as _i8;
import 'package:image_picker/image_picker.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [VideoRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockVideoRepository extends _i1.Mock implements _i2.VideoRepository {
  MockVideoRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.SelectedVideo?> pickVideo(_i5.ImageSource? source) =>
      (super.noSuchMethod(
            Invocation.method(#pickVideo, [source]),
            returnValue: _i3.Future<_i4.SelectedVideo?>.value(),
          )
          as _i3.Future<_i4.SelectedVideo?>);
}

/// A class which mocks [StorageRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageRepository extends _i1.Mock implements _i6.StorageRepository {
  MockStorageRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String> uploadToStorage(_i4.SelectedVideo? video) =>
      (super.noSuchMethod(
            Invocation.method(#uploadToStorage, [video]),
            returnValue: _i3.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#uploadToStorage, [video]),
              ),
            ),
          )
          as _i3.Future<String>);
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i8.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String?> submitAnalysisJob({
    required String? storageReference,
    required String? email,
    required _i9.DanceStyle? danceStyle,
    List<_i10.VideoTimestamp>? timestamps = const [],
    Duration? trimStart = Duration.zero,
    Duration? trimEnd,
    required Duration? videoDuration,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#submitAnalysisJob, [], {
              #storageReference: storageReference,
              #email: email,
              #danceStyle: danceStyle,
              #timestamps: timestamps,
              #trimStart: trimStart,
              #trimEnd: trimEnd,
              #videoDuration: videoDuration,
            }),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);
}
